name: C# basics - build

on:
  push:
    branches: [ master ]
    
    paths:
      - '01-csharp-basics/**'

jobs:
 
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./01-csharp-basics/CSharpBasics/CSharpBasics.sln
    - name: Build Debug
      run: dotnet build ./01-csharp-basics/CSharpBasics/CSharpBasics.sln --configuration Debug --no-restore
    - name: Build Release
      run: dotnet build ./01-csharp-basics/CSharpBasics/CSharpBasics.sln --configuration Release --no-restore
