name: Arrays and methods - build

on:
  push:
    branches: [ master ]
    paths:
      - '02-arrays-and-methods/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./02-arrays-and-methods/ArraysAndMethods/ArraysAndMethods.sln
    - name: Build Debug
      run: dotnet build ./02-arrays-and-methods/ArraysAndMethods/ArraysAndMethods.sln --configuration Debug --no-restore
    - name: Build Release
      run: dotnet build ./02-arrays-and-methods/ArraysAndMethods/ArraysAndMethods.sln --configuration Release --no-restore
