name: Reference types - build

on:
  push:
    branches: [ master ]
    paths:
      - '04-reference-types/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./04-reference-types/ReferenceTypes/ReferenceTypes.sln
    - name: Build Debug
      run: dotnet build ./04-reference-types/ReferenceTypes/ReferenceTypes.sln --configuration Debug --no-restore
    - name: Build Release
      run: dotnet build ./04-reference-types/ReferenceTypes/ReferenceTypes.sln --configuration Release --no-restore
