name: .NET basics - build

on:
  push:
    branches: [ master ]
    paths:
      - '10-dotnet-basics/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./10-dotnet-basics/DotnetBasics/DotnetBasics.sln
    - name: Build Debug
      run: dotnet build ./10-dotnet-basics/DotnetBasics/DotnetBasics.sln --configuration Debug --no-restore
    - name: Build Release
      run: dotnet build ./10-dotnet-basics/DotnetBasics/DotnetBasics.sln --configuration Release --no-restore
